// This file is generated automatically by the PYLON build process
// DO NOT EDIT

#define PYLON_VERSION_MAJOR 3
#define PYLON_VERSION_MINOR 2
#define PYLON_VERSION_SUBMINOR 0
#define PYLON_VERSION_BUILD 0
#define PYLON_VERSIONSTRING_MAJOR "03"
#define PYLON_VERSIONSTRING_MINOR "02"
#define PYLON_VERSIONSTRING_SUBMINOR "00"
#define PYLON_VERSIONSTRING_BUILD "0000"
